name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '12.22.11'  # 将 Node.js 版本更改为 12.22.11

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.22.11'  # 将 Node.js 版本更改为 12.22.11

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.0'  # 将 PHP 版本更改为 7.0

    - name: Install Node.js dependencies
      run: npm install 

    - name: Install PHP dependencies
      run: composer install

    - name: Run tests
      run: |
        npm test  
        phpunit
